books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": "1234",
        "language": "English",
    },
    {
        "id": 2,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-03-31",
        "page_count": "1014",
        "language": "English",
    },
    {
        "id": 3,
        "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": "464",
        "language": "English",
    },
    {
        "id": 4,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt, David Thomas",
        "publisher": "Addison-Wesley Professional",
        "published_date": "2019-09-13",
        "page_count": "352",
        "language": "English",
    },
    {
        "id": 5,
        "title": "Designing Data-Intensive Applications",
        "author": "Martin Kleppmann",
        "publisher": "O'Reilly Media",
        "published_date": "2017-03-16",
        "page_count": "616",
        "language": "English",
    },
    {
        "id": 6,
        "title": "Introduction to Algorithms",
        "author": "Thomas H. Cormen, Charles E. Leiserson",
        "publisher": "MIT Press",
        "published_date": "2022-04-05",
        "page_count": "1312",
        "language": "English",
    },
    {
        "id": 7,
        "title": "Refactoring: Improving the Design of Existing Code",
        "author": "Martin Fowler",
        "publisher": "Addison-Wesley Professional",
        "published_date": "2018-11-19",
        "page_count": "448",
        "language": "English",
    },
    {
        "id": 8,
        "title": "Deep Learning",
        "author": "Ian Goodfellow, Yoshua Bengio",
        "publisher": "MIT Press",
        "published_date": "2016-11-18",
        "page_count": "800",
        "language": "English",
    },
    {
        "id": 9,
        "title": "Cracking the Coding Interview",
        "author": "Gayle Laakmann McDowell",
        "publisher": "CareerCup",
        "published_date": "2015-07-01",
        "page_count": "687",
        "language": "English",
    },
    {
        "id": 10,
        "title": "You Don't Know JS Yet: Get Started",
        "author": "Kyle Simpson",
        "publisher": "Leanpub",
        "published_date": "2020-01-28",
        "page_count": "145",
        "language": "English",
    },
]
